### PR TITLE
Update "TwCenMTStd" font

### LINKED ISSUE #97: Font Spacing Issue
Some characters, specifically the `1` character does not display correctly with the chosen font.  Can the font please be changed to make sure that the `1` displays as it should.

imagen

*As you can see, there is a lot of spacing before the `1`, meaning may just need shifting to the left*

### PR DESCRIPTION
**Pull request by tomfairey**
+ This update modifies the font to have less spacing at the front of the "1" character with the hope that Minecraft now renders this correctly without 'chopping off' the end spacing and fixes #97.
* I can't be sure of the font license but as it was offered on a free commercial use license, assume this modification is allowed

@gingerchicken Please build and confirm the changes work as expected then allow/block as required - I am currently unable to build and test

### CODE REVIEW

**Comment by gingerchicken** [comment]
What is with the commit names lol

**Comment by tomfairey** [comment]
> What is with the commit names lol

My bad, I forgot for a second that #X links to issues/PRs etc.

**Comment by tomfairey** [comment]
This latest commit appears to fix the issue though, I'd recommend for PR approval...

image

**Comment by gingerchicken** [comment]
Yeah that seems to make it way less extreme on the spacing, so it does appear to work.
imagen

**Review by gingerchicken — COMMENTED** [review]
Seems all good - updated only the font

**Pull request merged**
